// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkXDqaDzCOWR3B3b-6LXrhvFTsVvoPeNo',
    appId: '1:1067193033534:web:6c5279505486d3af06426f',
    messagingSenderId: '1067193033534',
    projectId: 'chat-6295d',
    authDomain: 'chat-6295d.firebaseapp.com',
    storageBucket: 'chat-6295d.appspot.com',
    measurementId: 'G-4F16E68FZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuIpyWV4RTwb2YXJ8mACEYWQ59N-RyM8U',
    appId: '1:1067193033534:android:ec3c1d814f7a5ef006426f',
    messagingSenderId: '1067193033534',
    projectId: 'chat-6295d',
    storageBucket: 'chat-6295d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvjZGfkMNMeHAomsUIGwIoeVaybIhzmCw',
    appId: '1:1067193033534:ios:5368491b5a5be33206426f',
    messagingSenderId: '1067193033534',
    projectId: 'chat-6295d',
    storageBucket: 'chat-6295d.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
